### ISSUE TITLE
Cmake dosen't want to work.

### ISSUE THREAD

**Issue by CzrCraft** [synthels/phiOS#1]
I was following the steps to building this OS, but i encountered an error. When i try to run the first cmake command, it gives me an error. I'm currently on Linux mint.
Here is the output:

DCMAKE_C_COMPILER=i686-elf-gcc -DCMAKE_TOOLCHAIN_FILE=cmake/x86.cmake -DARCH=x86_32 ..
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    i686-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/czrcaft/Desktop/PhiOs/phiOS-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/czrcaft/Desktop/PhiOs/phiOS-master/build/CMakeFiles/CMakeError.log".

Il also attach the log files.
[CMakeError.log](https://github.com/synthels/phiOS/files/6564073/CMakeError.log)
[CMakeOutput.log](https://github.com/synthels/phiOS/files/6564074/CMakeOutput.log)

I found the compiler on a website(https://formulae.brew.sh/formula-linux/i686-elf-gcc), but i cant get it to fully compile. When i try to build it, it finds multiple instances of "tty_row" and "tty_colum" etc. The compiler is fighting with a specific file.

I just get a lot of these errors:
/home/linuxbrew/.linuxbrew/opt/i686-elf-binutils/bin/i686-elf-ld: CMakeFiles/kernel.bin.dir/kernel/libk/malloc.c.obj:(.bss+0x10): multiple definition of `tty_row'; CMakeFiles/kernel.bin.dir/kernel/drivers/keyboard/keyboard.c.obj:(.bss+0xc): first defined here

**Comment by CzrCraft** [comment]
Nevermind! I found the compiler on a homebrew site.
https://formulae.brew.sh/formula-linux/i686-elf-gcc

**Comment by synthels** [comment]
You have to build the toolchain yourself. Try the `toolchain.sh` script under the scripts directory. As for the errors, everything compiles fine under my machine. Please tell me exactly what you did to compile. Thank you for taking an interest in my kernel!

**Comment by synthels** [comment]
Ah, I see what you're referring to. Building under a newer gcc also presents me with those same issues. I will fix them all and get back to you.

**Comment by synthels** [comment]
Thank you for bringing these errors to my attention! They should all be fixed now and you should be able to compile under your more recent gcc. There is still a very nasty bug that causes the CPU to triple fault immediately when the kernel starts. The IDT is probably at fault. If you could check whether the same crashes happen on your machine, I would be forever grateful.

**Comment by CzrCraft** [comment]
> Thank you for bringing these errors to my attention! They should all be fixed now and you should be able to compile under your more recent gcc. There is still a very nasty bug that causes the CPU to triple fault immediately when the kernel starts. The IDT is probably at fault. If you could check whether the same crashes happen on your machine, I would be forever grateful.

**Comment by CzrCraft** [comment]
Thank you for fixing this! I'll try the kernel on my machine in a few days as I'm not currently able to.
